import Foundation
import CryptoKit

struct KnowledgeFact: Codable, Hashable, Sendable { let text:String; let quote:String; let start:Int; let end:Int }
enum CharacterAttributeKind:String,Codable,Sendable{case alias="ALIAS",age="AGE",gender="GENDER",identity="IDENTITY",appearance="APPEARANCE"}
struct KnowledgeCharacterAttribute:Codable,Hashable,Sendable{let kind:CharacterAttributeKind;let value:String;let fact:KnowledgeFact}
struct KnowledgeCharacterRelationship:Codable,Hashable,Sendable{let target:String;let relation:String;let fact:KnowledgeFact}
struct KnowledgeCharacter:Codable,Hashable,Sendable{let name:String;let facts:[KnowledgeFact];let attributes:[KnowledgeCharacterAttribute];let relationships:[KnowledgeCharacterRelationship]}
struct ChapterKnowledge:Codable,Hashable,Sendable{let summary:[KnowledgeFact];let characters:[KnowledgeCharacter];let outline:String;var readableOutline:String{outline.isEmpty ? summary.map(\.text).joined(separator:"\n\n"):outline}}
struct KnowledgePart:Sendable{let start:Int;let text:String}

private struct KnowledgeDraft:Decodable{struct Fact:Decodable{let text:String;let quote:String};struct Attribute:Decodable{let kind:CharacterAttributeKind;let value:String;let quote:String};struct Relationship:Decodable{let target:String;let relation:String;let quote:String};struct Character:Decodable{let name:String;let facts:[Fact];let attributes:[Attribute]?;let relationships:[Relationship]?};let outline:String;let summary:[Fact];let characters:[Character]?}

enum ChapterKnowledgeCodec {
    static let promptVersion=2,maxSourceUTF16=60_000,partUTF16=10_000
    static func parts(_ source:String,enforceLimit:Bool=true)throws->[KnowledgePart]{let ns=source as NSString;guard ns.length>0,(!enforceLimit || ns.length<=maxSourceUTF16) else{throw KnowledgeError.invalid("每章最多整理 60000 字已读内容")};var out:[KnowledgePart]=[];var start=0;while start<ns.length{var end=min(ns.length,start+partUTF16);if end<ns.length{let floor=start+partUTF16/2;for i in stride(from:end-1,through:floor,by:-1){let c=ns.character(at:i);if [10,0x3002,0xff01,0xff1f,46,33,63].contains(Int(c)){end=i+1;break}}};out.append(.init(start:start,text:ns.substring(with:NSRange(location:start,length:end-start))));start=end};return out}
    static func parse(_ raw:String,part:KnowledgePart,maxOutlineUTF16:Int=2400)throws->ChapterKnowledge{let clean=stripFence(raw);guard let data=clean.data(using:.utf8),let d=try? JSONDecoder().decode(KnowledgeDraft.self,from:data) else{throw KnowledgeError.invalid("整理结果格式不完整，请重试")};guard (1...8).contains(d.summary.count),(d.characters?.count ?? 0)<=16 else{throw KnowledgeError.invalid("整理结果条目过多或缺少摘要")};let facts=try d.summary.map{try verify($0,part:part)};let chars=try (d.characters ?? []).map{try verifyCharacter($0,part:part)};let outline=try validateOutline(d.outline,limit:maxOutlineUTF16);return .init(summary:facts,characters:chars,outline:outline)}
    static func merge(_ parts:[ChapterKnowledge])->ChapterKnowledge{var facts:[KnowledgeFact]=[];var map:[String:KnowledgeCharacter]=[:];for p in parts{for f in p.summary where !facts.contains(f){facts.append(f)};for c in p.characters{if let old=map[c.name]{map[c.name] = .init(name:c.name,facts:Array(Set(old.facts+c.facts)),attributes:Array(Set(old.attributes+c.attributes)),relationships:Array(Set(old.relationships+c.relationships)))}else{map[c.name] = c}}};return .init(summary:facts,characters:Array(map.values).sorted{$0.name<$1.name},outline:parts.map(\.readableOutline).joined(separator:"\n\n"))}
    static func validateOutline(_ value:String,limit:Int)throws->String{let s=value.trimmingCharacters(in:.whitespacesAndNewlines);let n=(s as NSString).length;guard n>0,n<=limit else{throw KnowledgeError.invalid("请按要求生成长度适中的章节梗概")};let re=try! NSRegularExpression(pattern:#"(?m)^\s*(?:[-*•]|[0-9]+[.)、])\s+"#);guard re.firstMatch(in:s,range:NSRange(location:0,length:n))==nil else{throw KnowledgeError.invalid("请写成连贯自然段，不要罗列分散要点")};return s}
    static func hash(_ text:String)->String{SHA256.hash(data:Data(text.utf8)).map{String(format:"%02x",$0)}.joined()}
    private static func verify(_ f:KnowledgeDraft.Fact,part:KnowledgePart)throws->KnowledgeFact{let text=f.text.trimmingCharacters(in:.whitespacesAndNewlines),quote=f.quote.trimmingCharacters(in:.whitespacesAndNewlines);let qlen=(quote as NSString).length;guard !(text.isEmpty),qlen>=4,qlen<=300 else{throw KnowledgeError.invalid("整理结果缺少简短描述或原文依据")};let ns=part.text as NSString;let first=ns.range(of:quote);guard first.location != NSNotFound else{throw KnowledgeError.invalid("引文无法在原文核对")};let after=NSMaxRange(first);let second=after<ns.length ? ns.range(of:quote,range:NSRange(location:after,length:ns.length-after)):NSRange(location:NSNotFound,length:0);guard second.location==NSNotFound else{throw KnowledgeError.invalid("部分引文无法唯一核对，请重新整理")};return .init(text:String(text.prefix(600)),quote:quote,start:part.start+first.location,end:part.start+NSMaxRange(first))}
    private static func verifyCharacter(_ c:KnowledgeDraft.Character,part:KnowledgePart)throws->KnowledgeCharacter{let name=c.name.trimmingCharacters(in:.whitespacesAndNewlines);guard !name.isEmpty,!Set(["他","她","我","你","他们","她们","旁白"]).contains(name),(part.text as NSString).range(of:name).location != NSNotFound,(1...4).contains(c.facts.count) else{throw KnowledgeError.invalid("人物资料格式无效")};let facts=try c.facts.map{try verify($0,part:part)};let attrs=try (c.attributes ?? []).prefix(12).map{a in guard !a.value.isEmpty,a.quote.contains(name) else{throw KnowledgeError.invalid("属性引文需包含人物称呼")};if a.kind == .alias && (!a.quote.contains(a.value)||a.value==name){throw KnowledgeError.invalid("别名需在同一段原文中明确关联")};return KnowledgeCharacterAttribute(kind:a.kind,value:a.value,fact:try verify(.init(text:a.value,quote:a.quote),part:part))};let rels=try (c.relationships ?? []).prefix(12).map{r in guard !r.target.isEmpty,r.target != name,r.quote.contains(name),r.quote.contains(r.target) else{throw KnowledgeError.invalid("关系引文需包含双方姓名或稳定称呼")};return KnowledgeCharacterRelationship(target:r.target,relation:r.relation,fact:try verify(.init(text:"\(name) → \(r.target)：\(r.relation)",quote:r.quote),part:part))};return .init(name:name,facts:facts,attributes:Array(attrs),relationships:Array(rels))}
    private static func stripFence(_ s:String)->String{s.trimmingCharacters(in:.whitespacesAndNewlines).replacingOccurrences(of:"```json",with:"").replacingOccurrences(of:"```",with:"").trimmingCharacters(in:.whitespacesAndNewlines)}
    struct KnowledgeError:LocalizedError{let message:String;static func invalid(_ s:String)->Self{.init(message:s)};var errorDescription:String?{message}}
}
