import SwiftUI

struct PlotSummaryView:View{
    let book:Book
    @Environment(\.dismiss) private var dismiss
    @State private var notes:[ReaderNote]=[];@State private var personas:[PersonaRecord]=[];@State private var personaId:Int64?;@State private var instruction="";@State private var running=false;@State private var error:String?
    var body:some View{NavigationStack{List{Section{Picker("伴读角色",selection:Binding<Int64?>(get:{personaId},set:{personaId=$0})){Text("默认").tag(Int64?.none);ForEach(personas){Text($0.name).tag(Optional($0.id))}};TextField("侧重点（可选）",text:$instruction,axis:.vertical);Button(running ? "正在整理…":"按当前已读范围生成剧情梗概"){generate()}.disabled(running)};Section("已有剧情梗概"){if notes.isEmpty{Text("还没有剧情梗概").foregroundStyle(.secondary)};ForEach(notes){n in VStack(alignment:.leading,spacing:6){Text(n.title).font(.headline);Text(n.contentMarkdown).textSelection(.enabled);Text(Date(timeIntervalSince1970:Double(n.updatedAt)/1000),style:.date).font(.caption).foregroundStyle(.secondary)}}}}.navigationTitle("剧情梗概").toolbar{ToolbarItem(placement:.cancellationAction){Button("关闭"){dismiss()}}}.task{await load()}.alert("梗概生成失败",isPresented:Binding(get:{error != nil},set:{if !$0{error=nil}})){Button("好",role:.cancel){}}message:{Text(error ?? "")}}}
    @MainActor private func load()async{do{notes=try await NoteRepository.shared.notes(bookId:book.id).filter{$0.kind=="PLOT_SUMMARY"};personas=try await PersonaRepository.shared.personas()}catch{self.error=error.localizedDescription}}
    private func generate(){running=true;Task{@MainActor in do{let scope=ReadingScope.uptoProgress(book:book);let persona=personaId.flatMap{id in personas.first{$0.id==id}};let personaPrompt=await PersonaRepository.shared.systemPrompt(for:persona,triggerText:instruction);let system=personaPrompt+"\n\n整理这本书截至用户当前已读范围的剧情梗概。必须以书内只读工具核对事实，不得使用或暗示未读剧情。按人物、关键事件、未解决线索组织，清楚区分事实与推断。";let prompt="书名：《\(book.title)》\n侧重点：\(instruction.prefix(2000))";let text=try await ReadOnlyBookAgent.shared.run(bookId:book.id,scope:scope,personaId:personaId,messages:[.init(role:.system,content:system),.init(role:.user,content:prompt)],maxRounds:5);_ = try await NoteRepository.shared.savePlotSummary(bookId:book.id,personaId:personaId,title:"剧情梗概 · 读到第 \(scope.maxChapterIndex+1) 章",content:text,chapterIndex:scope.maxChapterIndex,charOffset:scope.maxCharOffset,scope:scope);await load()}catch{self.error=error.localizedDescription};running=false}}
}
