import Foundation

actor AudiobookPlanner {
    static let shared=AudiobookPlanner()

    func extractRoles(bookId:Int64,useAI:Bool=true)async throws->[AudiobookRole]{
        var names:[KnowledgeCharacter]=[]
        if let book=try await LibraryRepository.shared.book(id:bookId),let guide=try? await BookCharacterRepository.shared.published(bookId:bookId,scope:.uptoProgress(book:book)){names=guide.characters}
        var roles:[AudiobookRole]=[.init(bookId:bookId,name:"旁白",aliases:[],kind:.narrator,gender:"",engine:.system,voiceId:"",extraJSON:"{}",color:"#888888",sortOrder:0,source:"local")]
        for (i,ch) in names.prefix(24).enumerated(){let attrs=ch.attributes.map{"\($0.kind.rawValue):\($0.value)"}.joined(separator:", ");roles.append(.init(bookId:bookId,name:ch.name,aliases:ch.attributes.filter{$0.kind == .alias}.map(\.value),kind:.character,gender:ch.attributes.first{$0.kind == .gender}?.value ?? "",engine:.system,voiceId:"",extraJSON:"{\"profile\":\(jsonString(attrs))}",color:Self.color(i),sortOrder:i+1,source:"knowledge"))}
        if roles.count<=1 && useAI { roles += try await inferRolesFromText(bookId:bookId) }
        try await AudiobookRepository.shared.replaceRoles(bookId:bookId,roles);return try await AudiobookRepository.shared.roles(bookId:bookId)
    }

    func script(bookId:Int64,chapterIndex:Int,useAI:Bool=true)async throws->[AudiobookSegment]{
        guard let chapter=try await LibraryRepository.shared.chapter(bookId:bookId,index:chapterIndex) else{return []};let body=try await LibraryRepository.shared.chapterText(chapter);let rules=await MainActor.run{ReaderEnhancementSettingsStore.shared.settings.replacementRules};let roles=try await AudiobookRepository.shared.roles(bookId:bookId);let narrator=roles.first{$0.kind == .narrator};let spans=SentenceSegmenter.segmentParagraphs(body,maxChars:400)
        var result=spans.map{AudiobookSegment(bookId:bookId,chapterIndex:chapterIndex,start:$0.start,end:$0.end,roleId:attributedRole(body:body,span:$0,roles:roles)?.id ?? narrator?.id,emotion:nil,instruction:nil,audioPath:nil,audioMillis:0,revision:ReaderTextReplacementEngine.audiobookRevision(body,rules:rules))}
        if useAI,!roles.isEmpty,!result.isEmpty { result=try await refineAttribution(body:body,segments:result,roles:roles) }
        try await AudiobookRepository.shared.replaceSegments(bookId:bookId,chapterIndex:chapterIndex,result);return try await AudiobookRepository.shared.segments(bookId:bookId,chapterIndex:chapterIndex)
    }

    private func inferRolesFromText(bookId:Int64)async throws->[AudiobookRole]{let chapters=try await LibraryRepository.shared.chapters(bookId:bookId);var sample="";for c in chapters.prefix(4){sample += "\n"+String((try await LibraryRepository.shared.chapterText(c)).prefix(4000))};let resolved=try await AIClientFactory.forRole(.cheap);let raw=try await resolved.client.chat(messages:[.init(role:.user,content:"从小说样本提取主要人物，只输出 JSON 数组 [{\"name\":\"人物\",\"gender\":\"\",\"aliases\":[\"\"]}]，不要旁白，不猜测不存在的信息。样本：\n\(sample)")],options:resolved.options);guard let d=extractJSON(raw).data(using:.utf8),let arr=try? JSONSerialization.jsonObject(with:d) as? [[String:Any]] else{return []};return arr.prefix(24).enumerated().compactMap{i,o in guard let n=(o["name"] as? String)?.trimmingCharacters(in:.whitespacesAndNewlines),n.count>=1 else{return nil};return AudiobookRole(bookId:bookId,name:n,aliases:o["aliases"] as? [String] ?? [],kind:.character,gender:o["gender"] as? String ?? "",engine:.system,voiceId:"",extraJSON:"{}",color:Self.color(i),sortOrder:i+1,source:"ai")}}
    private func attributedRole(body:String,span:SentenceSpan,roles:[AudiobookRole])->AudiobookRole?{let text=(body as NSString).substring(with:NSRange(location:span.start,length:span.end-span.start));guard text.contains("“") || text.contains("「") || text.contains("\"") else{return nil};let nearbyStart=max(0,span.start-60);let nearby=(body as NSString).substring(with:NSRange(location:nearbyStart,length:span.end-nearbyStart));return roles.filter{$0.kind == .character}.first{r in ([r.name]+r.aliases).contains{nearby.contains($0)}}}
    private func refineAttribution(body:String,segments:[AudiobookSegment],roles:[AudiobookRole])async throws->[AudiobookSegment]{let unresolved=segments.enumerated().filter{$0.element.roleId == roles.first{$0.kind == .narrator}?.id && ((body as NSString).substring(with:NSRange(location:$0.element.start,length:$0.element.end-$0.element.start)).contains("“"))};guard !unresolved.isEmpty else{return segments};let candidates=roles.map{"\($0.id)|\($0.name)|\($0.aliases.joined(separator:","))"}.joined(separator:"\n");let lines=unresolved.prefix(80).map{"\($0.offset)|"+String((body as NSString).substring(with:NSRange(location:$0.element.start,length:$0.element.end-$0.element.start)).prefix(300))}.joined(separator:"\n");let resolved=try await AIClientFactory.forRole(.cheap);let raw=try await resolved.client.chat(messages:[.init(role:.user,content:"为有声书对白归属角色。候选角色：\n\(candidates)\n片段：\n\(lines)\n只输出 JSON 对象 {\"assignments\":{\"片段序号\":角色ID}}；不确定就用旁白 ID \(roles.first{$0.kind == .narrator}?.id ?? 0)，不能编造 ID。")],options:resolved.options);guard let d=extractJSON(raw).data(using:.utf8),let root=try? JSONSerialization.jsonObject(with:d) as? [String:Any],let a=root["assignments"] as? [String:Any] else{return segments};let valid=Set(roles.map(\.id));var out=segments;for(k,v) in a{guard let i=Int(k),out.indices.contains(i) else{continue};let rid=(v as? NSNumber)?.int64Value ?? Int64(v as? String ?? "") ?? 0;if valid.contains(rid){out[i].roleId=rid}};return out}
    private func extractJSON(_ raw:String)->String{let s=raw.replacingOccurrences(of:"```json",with:"").replacingOccurrences(of:"```",with:"").trimmingCharacters(in:.whitespacesAndNewlines);if let a=s.firstIndex(of:"["),let b=s.lastIndex(of:"]"){return String(s[a...b])};if let a=s.firstIndex(of:"{"),let b=s.lastIndex(of:"}"){return String(s[a...b])};return s}
    private static func color(_ i:Int)->String{["#E57373","#64B5F6","#81C784","#BA68C8","#FFB74D","#4DB6AC","#9575CD","#A1887F"][i%8]}
}
private func jsonString(_ s:String)->String{let d=try? JSONSerialization.data(withJSONObject:s);return d.flatMap{String(data:$0,encoding:.utf8)} ?? "\"\""}
